//! This file is automatically generated with the `generate_impl_rs.py` script.
//! It basically just finds all the number combinations for which a certain
//! trait should be implemented.

use super::{Bits, BitsDownCast, BitsConcat};

impl BitsDownCast<1> for Bits<1> {}
impl BitsConcat<1, 2> for Bits<1> {}
impl BitsDownCast<1> for Bits<2> {}
impl BitsConcat<1, 3> for Bits<2> {}
impl BitsDownCast<2> for Bits<2> {}
impl BitsConcat<2, 4> for Bits<2> {}
impl BitsDownCast<1> for Bits<3> {}
impl BitsConcat<1, 4> for Bits<3> {}
impl BitsDownCast<2> for Bits<3> {}
impl BitsConcat<2, 5> for Bits<3> {}
impl BitsDownCast<3> for Bits<3> {}
impl BitsConcat<3, 6> for Bits<3> {}
impl BitsDownCast<1> for Bits<4> {}
impl BitsConcat<1, 5> for Bits<4> {}
impl BitsDownCast<2> for Bits<4> {}
impl BitsConcat<2, 6> for Bits<4> {}
impl BitsDownCast<3> for Bits<4> {}
impl BitsConcat<3, 7> for Bits<4> {}
impl BitsDownCast<4> for Bits<4> {}
impl BitsConcat<4, 8> for Bits<4> {}
impl BitsDownCast<1> for Bits<5> {}
impl BitsConcat<1, 6> for Bits<5> {}
impl BitsDownCast<2> for Bits<5> {}
impl BitsConcat<2, 7> for Bits<5> {}
impl BitsDownCast<3> for Bits<5> {}
impl BitsConcat<3, 8> for Bits<5> {}
impl BitsDownCast<4> for Bits<5> {}
impl BitsConcat<4, 9> for Bits<5> {}
impl BitsDownCast<5> for Bits<5> {}
impl BitsConcat<5, 10> for Bits<5> {}
impl BitsDownCast<1> for Bits<6> {}
impl BitsConcat<1, 7> for Bits<6> {}
impl BitsDownCast<2> for Bits<6> {}
impl BitsConcat<2, 8> for Bits<6> {}
impl BitsDownCast<3> for Bits<6> {}
impl BitsConcat<3, 9> for Bits<6> {}
impl BitsDownCast<4> for Bits<6> {}
impl BitsConcat<4, 10> for Bits<6> {}
impl BitsDownCast<5> for Bits<6> {}
impl BitsConcat<5, 11> for Bits<6> {}
impl BitsDownCast<6> for Bits<6> {}
impl BitsConcat<6, 12> for Bits<6> {}
impl BitsDownCast<1> for Bits<7> {}
impl BitsConcat<1, 8> for Bits<7> {}
impl BitsDownCast<2> for Bits<7> {}
impl BitsConcat<2, 9> for Bits<7> {}
impl BitsDownCast<3> for Bits<7> {}
impl BitsConcat<3, 10> for Bits<7> {}
impl BitsDownCast<4> for Bits<7> {}
impl BitsConcat<4, 11> for Bits<7> {}
impl BitsDownCast<5> for Bits<7> {}
impl BitsConcat<5, 12> for Bits<7> {}
impl BitsDownCast<6> for Bits<7> {}
impl BitsConcat<6, 13> for Bits<7> {}
impl BitsDownCast<7> for Bits<7> {}
impl BitsConcat<7, 14> for Bits<7> {}
impl BitsDownCast<1> for Bits<8> {}
impl BitsConcat<1, 9> for Bits<8> {}
impl BitsDownCast<2> for Bits<8> {}
impl BitsConcat<2, 10> for Bits<8> {}
impl BitsDownCast<3> for Bits<8> {}
impl BitsConcat<3, 11> for Bits<8> {}
impl BitsDownCast<4> for Bits<8> {}
impl BitsConcat<4, 12> for Bits<8> {}
impl BitsDownCast<5> for Bits<8> {}
impl BitsConcat<5, 13> for Bits<8> {}
impl BitsDownCast<6> for Bits<8> {}
impl BitsConcat<6, 14> for Bits<8> {}
impl BitsDownCast<7> for Bits<8> {}
impl BitsConcat<7, 15> for Bits<8> {}
impl BitsDownCast<8> for Bits<8> {}
impl BitsConcat<8, 16> for Bits<8> {}
impl BitsDownCast<1> for Bits<9> {}
impl BitsConcat<1, 10> for Bits<9> {}
impl BitsDownCast<2> for Bits<9> {}
impl BitsConcat<2, 11> for Bits<9> {}
impl BitsDownCast<3> for Bits<9> {}
impl BitsConcat<3, 12> for Bits<9> {}
impl BitsDownCast<4> for Bits<9> {}
impl BitsConcat<4, 13> for Bits<9> {}
impl BitsDownCast<5> for Bits<9> {}
impl BitsConcat<5, 14> for Bits<9> {}
impl BitsDownCast<6> for Bits<9> {}
impl BitsConcat<6, 15> for Bits<9> {}
impl BitsDownCast<7> for Bits<9> {}
impl BitsConcat<7, 16> for Bits<9> {}
impl BitsDownCast<8> for Bits<9> {}
impl BitsConcat<8, 17> for Bits<9> {}
impl BitsDownCast<9> for Bits<9> {}
impl BitsConcat<9, 18> for Bits<9> {}
impl BitsDownCast<1> for Bits<10> {}
impl BitsConcat<1, 11> for Bits<10> {}
impl BitsDownCast<2> for Bits<10> {}
impl BitsConcat<2, 12> for Bits<10> {}
impl BitsDownCast<3> for Bits<10> {}
impl BitsConcat<3, 13> for Bits<10> {}
impl BitsDownCast<4> for Bits<10> {}
impl BitsConcat<4, 14> for Bits<10> {}
impl BitsDownCast<5> for Bits<10> {}
impl BitsConcat<5, 15> for Bits<10> {}
impl BitsDownCast<6> for Bits<10> {}
impl BitsConcat<6, 16> for Bits<10> {}
impl BitsDownCast<7> for Bits<10> {}
impl BitsConcat<7, 17> for Bits<10> {}
impl BitsDownCast<8> for Bits<10> {}
impl BitsConcat<8, 18> for Bits<10> {}
impl BitsDownCast<9> for Bits<10> {}
impl BitsConcat<9, 19> for Bits<10> {}
impl BitsDownCast<10> for Bits<10> {}
impl BitsConcat<10, 20> for Bits<10> {}
impl BitsDownCast<1> for Bits<11> {}
impl BitsConcat<1, 12> for Bits<11> {}
impl BitsDownCast<2> for Bits<11> {}
impl BitsConcat<2, 13> for Bits<11> {}
impl BitsDownCast<3> for Bits<11> {}
impl BitsConcat<3, 14> for Bits<11> {}
impl BitsDownCast<4> for Bits<11> {}
impl BitsConcat<4, 15> for Bits<11> {}
impl BitsDownCast<5> for Bits<11> {}
impl BitsConcat<5, 16> for Bits<11> {}
impl BitsDownCast<6> for Bits<11> {}
impl BitsConcat<6, 17> for Bits<11> {}
impl BitsDownCast<7> for Bits<11> {}
impl BitsConcat<7, 18> for Bits<11> {}
impl BitsDownCast<8> for Bits<11> {}
impl BitsConcat<8, 19> for Bits<11> {}
impl BitsDownCast<9> for Bits<11> {}
impl BitsConcat<9, 20> for Bits<11> {}
impl BitsDownCast<10> for Bits<11> {}
impl BitsConcat<10, 21> for Bits<11> {}
impl BitsDownCast<11> for Bits<11> {}
impl BitsConcat<11, 22> for Bits<11> {}
impl BitsDownCast<1> for Bits<12> {}
impl BitsConcat<1, 13> for Bits<12> {}
impl BitsDownCast<2> for Bits<12> {}
impl BitsConcat<2, 14> for Bits<12> {}
impl BitsDownCast<3> for Bits<12> {}
impl BitsConcat<3, 15> for Bits<12> {}
impl BitsDownCast<4> for Bits<12> {}
impl BitsConcat<4, 16> for Bits<12> {}
impl BitsDownCast<5> for Bits<12> {}
impl BitsConcat<5, 17> for Bits<12> {}
impl BitsDownCast<6> for Bits<12> {}
impl BitsConcat<6, 18> for Bits<12> {}
impl BitsDownCast<7> for Bits<12> {}
impl BitsConcat<7, 19> for Bits<12> {}
impl BitsDownCast<8> for Bits<12> {}
impl BitsConcat<8, 20> for Bits<12> {}
impl BitsDownCast<9> for Bits<12> {}
impl BitsConcat<9, 21> for Bits<12> {}
impl BitsDownCast<10> for Bits<12> {}
impl BitsConcat<10, 22> for Bits<12> {}
impl BitsDownCast<11> for Bits<12> {}
impl BitsConcat<11, 23> for Bits<12> {}
impl BitsDownCast<12> for Bits<12> {}
impl BitsConcat<12, 24> for Bits<12> {}
impl BitsDownCast<1> for Bits<13> {}
impl BitsConcat<1, 14> for Bits<13> {}
impl BitsDownCast<2> for Bits<13> {}
impl BitsConcat<2, 15> for Bits<13> {}
impl BitsDownCast<3> for Bits<13> {}
impl BitsConcat<3, 16> for Bits<13> {}
impl BitsDownCast<4> for Bits<13> {}
impl BitsConcat<4, 17> for Bits<13> {}
impl BitsDownCast<5> for Bits<13> {}
impl BitsConcat<5, 18> for Bits<13> {}
impl BitsDownCast<6> for Bits<13> {}
impl BitsConcat<6, 19> for Bits<13> {}
impl BitsDownCast<7> for Bits<13> {}
impl BitsConcat<7, 20> for Bits<13> {}
impl BitsDownCast<8> for Bits<13> {}
impl BitsConcat<8, 21> for Bits<13> {}
impl BitsDownCast<9> for Bits<13> {}
impl BitsConcat<9, 22> for Bits<13> {}
impl BitsDownCast<10> for Bits<13> {}
impl BitsConcat<10, 23> for Bits<13> {}
impl BitsDownCast<11> for Bits<13> {}
impl BitsConcat<11, 24> for Bits<13> {}
impl BitsDownCast<12> for Bits<13> {}
impl BitsConcat<12, 25> for Bits<13> {}
impl BitsDownCast<13> for Bits<13> {}
impl BitsConcat<13, 26> for Bits<13> {}
impl BitsDownCast<1> for Bits<14> {}
impl BitsConcat<1, 15> for Bits<14> {}
impl BitsDownCast<2> for Bits<14> {}
impl BitsConcat<2, 16> for Bits<14> {}
impl BitsDownCast<3> for Bits<14> {}
impl BitsConcat<3, 17> for Bits<14> {}
impl BitsDownCast<4> for Bits<14> {}
impl BitsConcat<4, 18> for Bits<14> {}
impl BitsDownCast<5> for Bits<14> {}
impl BitsConcat<5, 19> for Bits<14> {}
impl BitsDownCast<6> for Bits<14> {}
impl BitsConcat<6, 20> for Bits<14> {}
impl BitsDownCast<7> for Bits<14> {}
impl BitsConcat<7, 21> for Bits<14> {}
impl BitsDownCast<8> for Bits<14> {}
impl BitsConcat<8, 22> for Bits<14> {}
impl BitsDownCast<9> for Bits<14> {}
impl BitsConcat<9, 23> for Bits<14> {}
impl BitsDownCast<10> for Bits<14> {}
impl BitsConcat<10, 24> for Bits<14> {}
impl BitsDownCast<11> for Bits<14> {}
impl BitsConcat<11, 25> for Bits<14> {}
impl BitsDownCast<12> for Bits<14> {}
impl BitsConcat<12, 26> for Bits<14> {}
impl BitsDownCast<13> for Bits<14> {}
impl BitsConcat<13, 27> for Bits<14> {}
impl BitsDownCast<14> for Bits<14> {}
impl BitsConcat<14, 28> for Bits<14> {}
impl BitsDownCast<1> for Bits<15> {}
impl BitsConcat<1, 16> for Bits<15> {}
impl BitsDownCast<2> for Bits<15> {}
impl BitsConcat<2, 17> for Bits<15> {}
impl BitsDownCast<3> for Bits<15> {}
impl BitsConcat<3, 18> for Bits<15> {}
impl BitsDownCast<4> for Bits<15> {}
impl BitsConcat<4, 19> for Bits<15> {}
impl BitsDownCast<5> for Bits<15> {}
impl BitsConcat<5, 20> for Bits<15> {}
impl BitsDownCast<6> for Bits<15> {}
impl BitsConcat<6, 21> for Bits<15> {}
impl BitsDownCast<7> for Bits<15> {}
impl BitsConcat<7, 22> for Bits<15> {}
impl BitsDownCast<8> for Bits<15> {}
impl BitsConcat<8, 23> for Bits<15> {}
impl BitsDownCast<9> for Bits<15> {}
impl BitsConcat<9, 24> for Bits<15> {}
impl BitsDownCast<10> for Bits<15> {}
impl BitsConcat<10, 25> for Bits<15> {}
impl BitsDownCast<11> for Bits<15> {}
impl BitsConcat<11, 26> for Bits<15> {}
impl BitsDownCast<12> for Bits<15> {}
impl BitsConcat<12, 27> for Bits<15> {}
impl BitsDownCast<13> for Bits<15> {}
impl BitsConcat<13, 28> for Bits<15> {}
impl BitsDownCast<14> for Bits<15> {}
impl BitsConcat<14, 29> for Bits<15> {}
impl BitsDownCast<15> for Bits<15> {}
impl BitsConcat<15, 30> for Bits<15> {}
impl BitsDownCast<1> for Bits<16> {}
impl BitsConcat<1, 17> for Bits<16> {}
impl BitsDownCast<2> for Bits<16> {}
impl BitsConcat<2, 18> for Bits<16> {}
impl BitsDownCast<3> for Bits<16> {}
impl BitsConcat<3, 19> for Bits<16> {}
impl BitsDownCast<4> for Bits<16> {}
impl BitsConcat<4, 20> for Bits<16> {}
impl BitsDownCast<5> for Bits<16> {}
impl BitsConcat<5, 21> for Bits<16> {}
impl BitsDownCast<6> for Bits<16> {}
impl BitsConcat<6, 22> for Bits<16> {}
impl BitsDownCast<7> for Bits<16> {}
impl BitsConcat<7, 23> for Bits<16> {}
impl BitsDownCast<8> for Bits<16> {}
impl BitsConcat<8, 24> for Bits<16> {}
impl BitsDownCast<9> for Bits<16> {}
impl BitsConcat<9, 25> for Bits<16> {}
impl BitsDownCast<10> for Bits<16> {}
impl BitsConcat<10, 26> for Bits<16> {}
impl BitsDownCast<11> for Bits<16> {}
impl BitsConcat<11, 27> for Bits<16> {}
impl BitsDownCast<12> for Bits<16> {}
impl BitsConcat<12, 28> for Bits<16> {}
impl BitsDownCast<13> for Bits<16> {}
impl BitsConcat<13, 29> for Bits<16> {}
impl BitsDownCast<14> for Bits<16> {}
impl BitsConcat<14, 30> for Bits<16> {}
impl BitsDownCast<15> for Bits<16> {}
impl BitsConcat<15, 31> for Bits<16> {}
impl BitsDownCast<16> for Bits<16> {}
impl BitsConcat<16, 32> for Bits<16> {}
impl BitsDownCast<1> for Bits<17> {}
impl BitsConcat<1, 18> for Bits<17> {}
impl BitsDownCast<2> for Bits<17> {}
impl BitsConcat<2, 19> for Bits<17> {}
impl BitsDownCast<3> for Bits<17> {}
impl BitsConcat<3, 20> for Bits<17> {}
impl BitsDownCast<4> for Bits<17> {}
impl BitsConcat<4, 21> for Bits<17> {}
impl BitsDownCast<5> for Bits<17> {}
impl BitsConcat<5, 22> for Bits<17> {}
impl BitsDownCast<6> for Bits<17> {}
impl BitsConcat<6, 23> for Bits<17> {}
impl BitsDownCast<7> for Bits<17> {}
impl BitsConcat<7, 24> for Bits<17> {}
impl BitsDownCast<8> for Bits<17> {}
impl BitsConcat<8, 25> for Bits<17> {}
impl BitsDownCast<9> for Bits<17> {}
impl BitsConcat<9, 26> for Bits<17> {}
impl BitsDownCast<10> for Bits<17> {}
impl BitsConcat<10, 27> for Bits<17> {}
impl BitsDownCast<11> for Bits<17> {}
impl BitsConcat<11, 28> for Bits<17> {}
impl BitsDownCast<12> for Bits<17> {}
impl BitsConcat<12, 29> for Bits<17> {}
impl BitsDownCast<13> for Bits<17> {}
impl BitsConcat<13, 30> for Bits<17> {}
impl BitsDownCast<14> for Bits<17> {}
impl BitsConcat<14, 31> for Bits<17> {}
impl BitsDownCast<15> for Bits<17> {}
impl BitsConcat<15, 32> for Bits<17> {}
impl BitsDownCast<16> for Bits<17> {}
impl BitsDownCast<17> for Bits<17> {}
impl BitsDownCast<1> for Bits<18> {}
impl BitsConcat<1, 19> for Bits<18> {}
impl BitsDownCast<2> for Bits<18> {}
impl BitsConcat<2, 20> for Bits<18> {}
impl BitsDownCast<3> for Bits<18> {}
impl BitsConcat<3, 21> for Bits<18> {}
impl BitsDownCast<4> for Bits<18> {}
impl BitsConcat<4, 22> for Bits<18> {}
impl BitsDownCast<5> for Bits<18> {}
impl BitsConcat<5, 23> for Bits<18> {}
impl BitsDownCast<6> for Bits<18> {}
impl BitsConcat<6, 24> for Bits<18> {}
impl BitsDownCast<7> for Bits<18> {}
impl BitsConcat<7, 25> for Bits<18> {}
impl BitsDownCast<8> for Bits<18> {}
impl BitsConcat<8, 26> for Bits<18> {}
impl BitsDownCast<9> for Bits<18> {}
impl BitsConcat<9, 27> for Bits<18> {}
impl BitsDownCast<10> for Bits<18> {}
impl BitsConcat<10, 28> for Bits<18> {}
impl BitsDownCast<11> for Bits<18> {}
impl BitsConcat<11, 29> for Bits<18> {}
impl BitsDownCast<12> for Bits<18> {}
impl BitsConcat<12, 30> for Bits<18> {}
impl BitsDownCast<13> for Bits<18> {}
impl BitsConcat<13, 31> for Bits<18> {}
impl BitsDownCast<14> for Bits<18> {}
impl BitsConcat<14, 32> for Bits<18> {}
impl BitsDownCast<15> for Bits<18> {}
impl BitsDownCast<16> for Bits<18> {}
impl BitsDownCast<17> for Bits<18> {}
impl BitsDownCast<18> for Bits<18> {}
impl BitsDownCast<1> for Bits<19> {}
impl BitsConcat<1, 20> for Bits<19> {}
impl BitsDownCast<2> for Bits<19> {}
impl BitsConcat<2, 21> for Bits<19> {}
impl BitsDownCast<3> for Bits<19> {}
impl BitsConcat<3, 22> for Bits<19> {}
impl BitsDownCast<4> for Bits<19> {}
impl BitsConcat<4, 23> for Bits<19> {}
impl BitsDownCast<5> for Bits<19> {}
impl BitsConcat<5, 24> for Bits<19> {}
impl BitsDownCast<6> for Bits<19> {}
impl BitsConcat<6, 25> for Bits<19> {}
impl BitsDownCast<7> for Bits<19> {}
impl BitsConcat<7, 26> for Bits<19> {}
impl BitsDownCast<8> for Bits<19> {}
impl BitsConcat<8, 27> for Bits<19> {}
impl BitsDownCast<9> for Bits<19> {}
impl BitsConcat<9, 28> for Bits<19> {}
impl BitsDownCast<10> for Bits<19> {}
impl BitsConcat<10, 29> for Bits<19> {}
impl BitsDownCast<11> for Bits<19> {}
impl BitsConcat<11, 30> for Bits<19> {}
impl BitsDownCast<12> for Bits<19> {}
impl BitsConcat<12, 31> for Bits<19> {}
impl BitsDownCast<13> for Bits<19> {}
impl BitsConcat<13, 32> for Bits<19> {}
impl BitsDownCast<14> for Bits<19> {}
impl BitsDownCast<15> for Bits<19> {}
impl BitsDownCast<16> for Bits<19> {}
impl BitsDownCast<17> for Bits<19> {}
impl BitsDownCast<18> for Bits<19> {}
impl BitsDownCast<19> for Bits<19> {}
impl BitsDownCast<1> for Bits<20> {}
impl BitsConcat<1, 21> for Bits<20> {}
impl BitsDownCast<2> for Bits<20> {}
impl BitsConcat<2, 22> for Bits<20> {}
impl BitsDownCast<3> for Bits<20> {}
impl BitsConcat<3, 23> for Bits<20> {}
impl BitsDownCast<4> for Bits<20> {}
impl BitsConcat<4, 24> for Bits<20> {}
impl BitsDownCast<5> for Bits<20> {}
impl BitsConcat<5, 25> for Bits<20> {}
impl BitsDownCast<6> for Bits<20> {}
impl BitsConcat<6, 26> for Bits<20> {}
impl BitsDownCast<7> for Bits<20> {}
impl BitsConcat<7, 27> for Bits<20> {}
impl BitsDownCast<8> for Bits<20> {}
impl BitsConcat<8, 28> for Bits<20> {}
impl BitsDownCast<9> for Bits<20> {}
impl BitsConcat<9, 29> for Bits<20> {}
impl BitsDownCast<10> for Bits<20> {}
impl BitsConcat<10, 30> for Bits<20> {}
impl BitsDownCast<11> for Bits<20> {}
impl BitsConcat<11, 31> for Bits<20> {}
impl BitsDownCast<12> for Bits<20> {}
impl BitsConcat<12, 32> for Bits<20> {}
impl BitsDownCast<13> for Bits<20> {}
impl BitsDownCast<14> for Bits<20> {}
impl BitsDownCast<15> for Bits<20> {}
impl BitsDownCast<16> for Bits<20> {}
impl BitsDownCast<17> for Bits<20> {}
impl BitsDownCast<18> for Bits<20> {}
impl BitsDownCast<19> for Bits<20> {}
impl BitsDownCast<20> for Bits<20> {}
impl BitsDownCast<1> for Bits<21> {}
impl BitsConcat<1, 22> for Bits<21> {}
impl BitsDownCast<2> for Bits<21> {}
impl BitsConcat<2, 23> for Bits<21> {}
impl BitsDownCast<3> for Bits<21> {}
impl BitsConcat<3, 24> for Bits<21> {}
impl BitsDownCast<4> for Bits<21> {}
impl BitsConcat<4, 25> for Bits<21> {}
impl BitsDownCast<5> for Bits<21> {}
impl BitsConcat<5, 26> for Bits<21> {}
impl BitsDownCast<6> for Bits<21> {}
impl BitsConcat<6, 27> for Bits<21> {}
impl BitsDownCast<7> for Bits<21> {}
impl BitsConcat<7, 28> for Bits<21> {}
impl BitsDownCast<8> for Bits<21> {}
impl BitsConcat<8, 29> for Bits<21> {}
impl BitsDownCast<9> for Bits<21> {}
impl BitsConcat<9, 30> for Bits<21> {}
impl BitsDownCast<10> for Bits<21> {}
impl BitsConcat<10, 31> for Bits<21> {}
impl BitsDownCast<11> for Bits<21> {}
impl BitsConcat<11, 32> for Bits<21> {}
impl BitsDownCast<12> for Bits<21> {}
impl BitsDownCast<13> for Bits<21> {}
impl BitsDownCast<14> for Bits<21> {}
impl BitsDownCast<15> for Bits<21> {}
impl BitsDownCast<16> for Bits<21> {}
impl BitsDownCast<17> for Bits<21> {}
impl BitsDownCast<18> for Bits<21> {}
impl BitsDownCast<19> for Bits<21> {}
impl BitsDownCast<20> for Bits<21> {}
impl BitsDownCast<21> for Bits<21> {}
impl BitsDownCast<1> for Bits<22> {}
impl BitsConcat<1, 23> for Bits<22> {}
impl BitsDownCast<2> for Bits<22> {}
impl BitsConcat<2, 24> for Bits<22> {}
impl BitsDownCast<3> for Bits<22> {}
impl BitsConcat<3, 25> for Bits<22> {}
impl BitsDownCast<4> for Bits<22> {}
impl BitsConcat<4, 26> for Bits<22> {}
impl BitsDownCast<5> for Bits<22> {}
impl BitsConcat<5, 27> for Bits<22> {}
impl BitsDownCast<6> for Bits<22> {}
impl BitsConcat<6, 28> for Bits<22> {}
impl BitsDownCast<7> for Bits<22> {}
impl BitsConcat<7, 29> for Bits<22> {}
impl BitsDownCast<8> for Bits<22> {}
impl BitsConcat<8, 30> for Bits<22> {}
impl BitsDownCast<9> for Bits<22> {}
impl BitsConcat<9, 31> for Bits<22> {}
impl BitsDownCast<10> for Bits<22> {}
impl BitsConcat<10, 32> for Bits<22> {}
impl BitsDownCast<11> for Bits<22> {}
impl BitsDownCast<12> for Bits<22> {}
impl BitsDownCast<13> for Bits<22> {}
impl BitsDownCast<14> for Bits<22> {}
impl BitsDownCast<15> for Bits<22> {}
impl BitsDownCast<16> for Bits<22> {}
impl BitsDownCast<17> for Bits<22> {}
impl BitsDownCast<18> for Bits<22> {}
impl BitsDownCast<19> for Bits<22> {}
impl BitsDownCast<20> for Bits<22> {}
impl BitsDownCast<21> for Bits<22> {}
impl BitsDownCast<22> for Bits<22> {}
impl BitsDownCast<1> for Bits<23> {}
impl BitsConcat<1, 24> for Bits<23> {}
impl BitsDownCast<2> for Bits<23> {}
impl BitsConcat<2, 25> for Bits<23> {}
impl BitsDownCast<3> for Bits<23> {}
impl BitsConcat<3, 26> for Bits<23> {}
impl BitsDownCast<4> for Bits<23> {}
impl BitsConcat<4, 27> for Bits<23> {}
impl BitsDownCast<5> for Bits<23> {}
impl BitsConcat<5, 28> for Bits<23> {}
impl BitsDownCast<6> for Bits<23> {}
impl BitsConcat<6, 29> for Bits<23> {}
impl BitsDownCast<7> for Bits<23> {}
impl BitsConcat<7, 30> for Bits<23> {}
impl BitsDownCast<8> for Bits<23> {}
impl BitsConcat<8, 31> for Bits<23> {}
impl BitsDownCast<9> for Bits<23> {}
impl BitsConcat<9, 32> for Bits<23> {}
impl BitsDownCast<10> for Bits<23> {}
impl BitsDownCast<11> for Bits<23> {}
impl BitsDownCast<12> for Bits<23> {}
impl BitsDownCast<13> for Bits<23> {}
impl BitsDownCast<14> for Bits<23> {}
impl BitsDownCast<15> for Bits<23> {}
impl BitsDownCast<16> for Bits<23> {}
impl BitsDownCast<17> for Bits<23> {}
impl BitsDownCast<18> for Bits<23> {}
impl BitsDownCast<19> for Bits<23> {}
impl BitsDownCast<20> for Bits<23> {}
impl BitsDownCast<21> for Bits<23> {}
impl BitsDownCast<22> for Bits<23> {}
impl BitsDownCast<23> for Bits<23> {}
impl BitsDownCast<1> for Bits<24> {}
impl BitsConcat<1, 25> for Bits<24> {}
impl BitsDownCast<2> for Bits<24> {}
impl BitsConcat<2, 26> for Bits<24> {}
impl BitsDownCast<3> for Bits<24> {}
impl BitsConcat<3, 27> for Bits<24> {}
impl BitsDownCast<4> for Bits<24> {}
impl BitsConcat<4, 28> for Bits<24> {}
impl BitsDownCast<5> for Bits<24> {}
impl BitsConcat<5, 29> for Bits<24> {}
impl BitsDownCast<6> for Bits<24> {}
impl BitsConcat<6, 30> for Bits<24> {}
impl BitsDownCast<7> for Bits<24> {}
impl BitsConcat<7, 31> for Bits<24> {}
impl BitsDownCast<8> for Bits<24> {}
impl BitsConcat<8, 32> for Bits<24> {}
impl BitsDownCast<9> for Bits<24> {}
impl BitsDownCast<10> for Bits<24> {}
impl BitsDownCast<11> for Bits<24> {}
impl BitsDownCast<12> for Bits<24> {}
impl BitsDownCast<13> for Bits<24> {}
impl BitsDownCast<14> for Bits<24> {}
impl BitsDownCast<15> for Bits<24> {}
impl BitsDownCast<16> for Bits<24> {}
impl BitsDownCast<17> for Bits<24> {}
impl BitsDownCast<18> for Bits<24> {}
impl BitsDownCast<19> for Bits<24> {}
impl BitsDownCast<20> for Bits<24> {}
impl BitsDownCast<21> for Bits<24> {}
impl BitsDownCast<22> for Bits<24> {}
impl BitsDownCast<23> for Bits<24> {}
impl BitsDownCast<24> for Bits<24> {}
impl BitsDownCast<1> for Bits<25> {}
impl BitsConcat<1, 26> for Bits<25> {}
impl BitsDownCast<2> for Bits<25> {}
impl BitsConcat<2, 27> for Bits<25> {}
impl BitsDownCast<3> for Bits<25> {}
impl BitsConcat<3, 28> for Bits<25> {}
impl BitsDownCast<4> for Bits<25> {}
impl BitsConcat<4, 29> for Bits<25> {}
impl BitsDownCast<5> for Bits<25> {}
impl BitsConcat<5, 30> for Bits<25> {}
impl BitsDownCast<6> for Bits<25> {}
impl BitsConcat<6, 31> for Bits<25> {}
impl BitsDownCast<7> for Bits<25> {}
impl BitsConcat<7, 32> for Bits<25> {}
impl BitsDownCast<8> for Bits<25> {}
impl BitsDownCast<9> for Bits<25> {}
impl BitsDownCast<10> for Bits<25> {}
impl BitsDownCast<11> for Bits<25> {}
impl BitsDownCast<12> for Bits<25> {}
impl BitsDownCast<13> for Bits<25> {}
impl BitsDownCast<14> for Bits<25> {}
impl BitsDownCast<15> for Bits<25> {}
impl BitsDownCast<16> for Bits<25> {}
impl BitsDownCast<17> for Bits<25> {}
impl BitsDownCast<18> for Bits<25> {}
impl BitsDownCast<19> for Bits<25> {}
impl BitsDownCast<20> for Bits<25> {}
impl BitsDownCast<21> for Bits<25> {}
impl BitsDownCast<22> for Bits<25> {}
impl BitsDownCast<23> for Bits<25> {}
impl BitsDownCast<24> for Bits<25> {}
impl BitsDownCast<25> for Bits<25> {}
impl BitsDownCast<1> for Bits<26> {}
impl BitsConcat<1, 27> for Bits<26> {}
impl BitsDownCast<2> for Bits<26> {}
impl BitsConcat<2, 28> for Bits<26> {}
impl BitsDownCast<3> for Bits<26> {}
impl BitsConcat<3, 29> for Bits<26> {}
impl BitsDownCast<4> for Bits<26> {}
impl BitsConcat<4, 30> for Bits<26> {}
impl BitsDownCast<5> for Bits<26> {}
impl BitsConcat<5, 31> for Bits<26> {}
impl BitsDownCast<6> for Bits<26> {}
impl BitsConcat<6, 32> for Bits<26> {}
impl BitsDownCast<7> for Bits<26> {}
impl BitsDownCast<8> for Bits<26> {}
impl BitsDownCast<9> for Bits<26> {}
impl BitsDownCast<10> for Bits<26> {}
impl BitsDownCast<11> for Bits<26> {}
impl BitsDownCast<12> for Bits<26> {}
impl BitsDownCast<13> for Bits<26> {}
impl BitsDownCast<14> for Bits<26> {}
impl BitsDownCast<15> for Bits<26> {}
impl BitsDownCast<16> for Bits<26> {}
impl BitsDownCast<17> for Bits<26> {}
impl BitsDownCast<18> for Bits<26> {}
impl BitsDownCast<19> for Bits<26> {}
impl BitsDownCast<20> for Bits<26> {}
impl BitsDownCast<21> for Bits<26> {}
impl BitsDownCast<22> for Bits<26> {}
impl BitsDownCast<23> for Bits<26> {}
impl BitsDownCast<24> for Bits<26> {}
impl BitsDownCast<25> for Bits<26> {}
impl BitsDownCast<26> for Bits<26> {}
impl BitsDownCast<1> for Bits<27> {}
impl BitsConcat<1, 28> for Bits<27> {}
impl BitsDownCast<2> for Bits<27> {}
impl BitsConcat<2, 29> for Bits<27> {}
impl BitsDownCast<3> for Bits<27> {}
impl BitsConcat<3, 30> for Bits<27> {}
impl BitsDownCast<4> for Bits<27> {}
impl BitsConcat<4, 31> for Bits<27> {}
impl BitsDownCast<5> for Bits<27> {}
impl BitsConcat<5, 32> for Bits<27> {}
impl BitsDownCast<6> for Bits<27> {}
impl BitsDownCast<7> for Bits<27> {}
impl BitsDownCast<8> for Bits<27> {}
impl BitsDownCast<9> for Bits<27> {}
impl BitsDownCast<10> for Bits<27> {}
impl BitsDownCast<11> for Bits<27> {}
impl BitsDownCast<12> for Bits<27> {}
impl BitsDownCast<13> for Bits<27> {}
impl BitsDownCast<14> for Bits<27> {}
impl BitsDownCast<15> for Bits<27> {}
impl BitsDownCast<16> for Bits<27> {}
impl BitsDownCast<17> for Bits<27> {}
impl BitsDownCast<18> for Bits<27> {}
impl BitsDownCast<19> for Bits<27> {}
impl BitsDownCast<20> for Bits<27> {}
impl BitsDownCast<21> for Bits<27> {}
impl BitsDownCast<22> for Bits<27> {}
impl BitsDownCast<23> for Bits<27> {}
impl BitsDownCast<24> for Bits<27> {}
impl BitsDownCast<25> for Bits<27> {}
impl BitsDownCast<26> for Bits<27> {}
impl BitsDownCast<27> for Bits<27> {}
impl BitsDownCast<1> for Bits<28> {}
impl BitsConcat<1, 29> for Bits<28> {}
impl BitsDownCast<2> for Bits<28> {}
impl BitsConcat<2, 30> for Bits<28> {}
impl BitsDownCast<3> for Bits<28> {}
impl BitsConcat<3, 31> for Bits<28> {}
impl BitsDownCast<4> for Bits<28> {}
impl BitsConcat<4, 32> for Bits<28> {}
impl BitsDownCast<5> for Bits<28> {}
impl BitsDownCast<6> for Bits<28> {}
impl BitsDownCast<7> for Bits<28> {}
impl BitsDownCast<8> for Bits<28> {}
impl BitsDownCast<9> for Bits<28> {}
impl BitsDownCast<10> for Bits<28> {}
impl BitsDownCast<11> for Bits<28> {}
impl BitsDownCast<12> for Bits<28> {}
impl BitsDownCast<13> for Bits<28> {}
impl BitsDownCast<14> for Bits<28> {}
impl BitsDownCast<15> for Bits<28> {}
impl BitsDownCast<16> for Bits<28> {}
impl BitsDownCast<17> for Bits<28> {}
impl BitsDownCast<18> for Bits<28> {}
impl BitsDownCast<19> for Bits<28> {}
impl BitsDownCast<20> for Bits<28> {}
impl BitsDownCast<21> for Bits<28> {}
impl BitsDownCast<22> for Bits<28> {}
impl BitsDownCast<23> for Bits<28> {}
impl BitsDownCast<24> for Bits<28> {}
impl BitsDownCast<25> for Bits<28> {}
impl BitsDownCast<26> for Bits<28> {}
impl BitsDownCast<27> for Bits<28> {}
impl BitsDownCast<28> for Bits<28> {}
impl BitsDownCast<1> for Bits<29> {}
impl BitsConcat<1, 30> for Bits<29> {}
impl BitsDownCast<2> for Bits<29> {}
impl BitsConcat<2, 31> for Bits<29> {}
impl BitsDownCast<3> for Bits<29> {}
impl BitsConcat<3, 32> for Bits<29> {}
impl BitsDownCast<4> for Bits<29> {}
impl BitsDownCast<5> for Bits<29> {}
impl BitsDownCast<6> for Bits<29> {}
impl BitsDownCast<7> for Bits<29> {}
impl BitsDownCast<8> for Bits<29> {}
impl BitsDownCast<9> for Bits<29> {}
impl BitsDownCast<10> for Bits<29> {}
impl BitsDownCast<11> for Bits<29> {}
impl BitsDownCast<12> for Bits<29> {}
impl BitsDownCast<13> for Bits<29> {}
impl BitsDownCast<14> for Bits<29> {}
impl BitsDownCast<15> for Bits<29> {}
impl BitsDownCast<16> for Bits<29> {}
impl BitsDownCast<17> for Bits<29> {}
impl BitsDownCast<18> for Bits<29> {}
impl BitsDownCast<19> for Bits<29> {}
impl BitsDownCast<20> for Bits<29> {}
impl BitsDownCast<21> for Bits<29> {}
impl BitsDownCast<22> for Bits<29> {}
impl BitsDownCast<23> for Bits<29> {}
impl BitsDownCast<24> for Bits<29> {}
impl BitsDownCast<25> for Bits<29> {}
impl BitsDownCast<26> for Bits<29> {}
impl BitsDownCast<27> for Bits<29> {}
impl BitsDownCast<28> for Bits<29> {}
impl BitsDownCast<29> for Bits<29> {}
impl BitsDownCast<1> for Bits<30> {}
impl BitsConcat<1, 31> for Bits<30> {}
impl BitsDownCast<2> for Bits<30> {}
impl BitsConcat<2, 32> for Bits<30> {}
impl BitsDownCast<3> for Bits<30> {}
impl BitsDownCast<4> for Bits<30> {}
impl BitsDownCast<5> for Bits<30> {}
impl BitsDownCast<6> for Bits<30> {}
impl BitsDownCast<7> for Bits<30> {}
impl BitsDownCast<8> for Bits<30> {}
impl BitsDownCast<9> for Bits<30> {}
impl BitsDownCast<10> for Bits<30> {}
impl BitsDownCast<11> for Bits<30> {}
impl BitsDownCast<12> for Bits<30> {}
impl BitsDownCast<13> for Bits<30> {}
impl BitsDownCast<14> for Bits<30> {}
impl BitsDownCast<15> for Bits<30> {}
impl BitsDownCast<16> for Bits<30> {}
impl BitsDownCast<17> for Bits<30> {}
impl BitsDownCast<18> for Bits<30> {}
impl BitsDownCast<19> for Bits<30> {}
impl BitsDownCast<20> for Bits<30> {}
impl BitsDownCast<21> for Bits<30> {}
impl BitsDownCast<22> for Bits<30> {}
impl BitsDownCast<23> for Bits<30> {}
impl BitsDownCast<24> for Bits<30> {}
impl BitsDownCast<25> for Bits<30> {}
impl BitsDownCast<26> for Bits<30> {}
impl BitsDownCast<27> for Bits<30> {}
impl BitsDownCast<28> for Bits<30> {}
impl BitsDownCast<29> for Bits<30> {}
impl BitsDownCast<30> for Bits<30> {}
impl BitsDownCast<1> for Bits<31> {}
impl BitsConcat<1, 32> for Bits<31> {}
impl BitsDownCast<2> for Bits<31> {}
impl BitsDownCast<3> for Bits<31> {}
impl BitsDownCast<4> for Bits<31> {}
impl BitsDownCast<5> for Bits<31> {}
impl BitsDownCast<6> for Bits<31> {}
impl BitsDownCast<7> for Bits<31> {}
impl BitsDownCast<8> for Bits<31> {}
impl BitsDownCast<9> for Bits<31> {}
impl BitsDownCast<10> for Bits<31> {}
impl BitsDownCast<11> for Bits<31> {}
impl BitsDownCast<12> for Bits<31> {}
impl BitsDownCast<13> for Bits<31> {}
impl BitsDownCast<14> for Bits<31> {}
impl BitsDownCast<15> for Bits<31> {}
impl BitsDownCast<16> for Bits<31> {}
impl BitsDownCast<17> for Bits<31> {}
impl BitsDownCast<18> for Bits<31> {}
impl BitsDownCast<19> for Bits<31> {}
impl BitsDownCast<20> for Bits<31> {}
impl BitsDownCast<21> for Bits<31> {}
impl BitsDownCast<22> for Bits<31> {}
impl BitsDownCast<23> for Bits<31> {}
impl BitsDownCast<24> for Bits<31> {}
impl BitsDownCast<25> for Bits<31> {}
impl BitsDownCast<26> for Bits<31> {}
impl BitsDownCast<27> for Bits<31> {}
impl BitsDownCast<28> for Bits<31> {}
impl BitsDownCast<29> for Bits<31> {}
impl BitsDownCast<30> for Bits<31> {}
impl BitsDownCast<31> for Bits<31> {}
impl BitsDownCast<1> for Bits<32> {}
impl BitsDownCast<2> for Bits<32> {}
impl BitsDownCast<3> for Bits<32> {}
impl BitsDownCast<4> for Bits<32> {}
impl BitsDownCast<5> for Bits<32> {}
impl BitsDownCast<6> for Bits<32> {}
impl BitsDownCast<7> for Bits<32> {}
impl BitsDownCast<8> for Bits<32> {}
impl BitsDownCast<9> for Bits<32> {}
impl BitsDownCast<10> for Bits<32> {}
impl BitsDownCast<11> for Bits<32> {}
impl BitsDownCast<12> for Bits<32> {}
impl BitsDownCast<13> for Bits<32> {}
impl BitsDownCast<14> for Bits<32> {}
impl BitsDownCast<15> for Bits<32> {}
impl BitsDownCast<16> for Bits<32> {}
impl BitsDownCast<17> for Bits<32> {}
impl BitsDownCast<18> for Bits<32> {}
impl BitsDownCast<19> for Bits<32> {}
impl BitsDownCast<20> for Bits<32> {}
impl BitsDownCast<21> for Bits<32> {}
impl BitsDownCast<22> for Bits<32> {}
impl BitsDownCast<23> for Bits<32> {}
impl BitsDownCast<24> for Bits<32> {}
impl BitsDownCast<25> for Bits<32> {}
impl BitsDownCast<26> for Bits<32> {}
impl BitsDownCast<27> for Bits<32> {}
impl BitsDownCast<28> for Bits<32> {}
impl BitsDownCast<29> for Bits<32> {}
impl BitsDownCast<30> for Bits<32> {}
impl BitsDownCast<31> for Bits<32> {}
impl BitsDownCast<32> for Bits<32> {}
